/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreatorSimulationInput = IDL.Record({
  'followersCount' : IDL.Nat,
  'platform' : IDL.Text,
  'niche' : IDL.Text,
  'averageViews' : IDL.Nat,
});
export const CreatorSimulationOutput = IDL.Record({
  'recommendations' : IDL.Vec(IDL.Text),
  'growthPotentialScore' : IDL.Int,
  'estimatedMonthlyIncome' : IDL.Int,
  'valuationGrade' : IDL.Text,
});
export const InvestorSimulationInput = IDL.Record({
  'followersCount' : IDL.Nat,
  'platform' : IDL.Text,
  'niche' : IDL.Text,
  'averageViews' : IDL.Nat,
});
export const InvestorSimulationOutput = IDL.Record({
  'brandDealValue' : IDL.Int,
  'cgnProjectedMonthlyRevenue' : IDL.Int,
  'estimatedCPM' : IDL.Float64,
  'roiScalingProjectionPercent' : IDL.Float64,
});

export const idlService = IDL.Service({
  'runCreatorSimulation' : IDL.Func(
      [CreatorSimulationInput],
      [CreatorSimulationOutput],
      ['query'],
    ),
  'runInvestorSimulation' : IDL.Func(
      [InvestorSimulationInput],
      [InvestorSimulationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreatorSimulationInput = IDL.Record({
    'followersCount' : IDL.Nat,
    'platform' : IDL.Text,
    'niche' : IDL.Text,
    'averageViews' : IDL.Nat,
  });
  const CreatorSimulationOutput = IDL.Record({
    'recommendations' : IDL.Vec(IDL.Text),
    'growthPotentialScore' : IDL.Int,
    'estimatedMonthlyIncome' : IDL.Int,
    'valuationGrade' : IDL.Text,
  });
  const InvestorSimulationInput = IDL.Record({
    'followersCount' : IDL.Nat,
    'platform' : IDL.Text,
    'niche' : IDL.Text,
    'averageViews' : IDL.Nat,
  });
  const InvestorSimulationOutput = IDL.Record({
    'brandDealValue' : IDL.Int,
    'cgnProjectedMonthlyRevenue' : IDL.Int,
    'estimatedCPM' : IDL.Float64,
    'roiScalingProjectionPercent' : IDL.Float64,
  });
  
  return IDL.Service({
    'runCreatorSimulation' : IDL.Func(
        [CreatorSimulationInput],
        [CreatorSimulationOutput],
        ['query'],
      ),
    'runInvestorSimulation' : IDL.Func(
        [InvestorSimulationInput],
        [InvestorSimulationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };